import type { Metadata } from "next";
import "./globals.css";
import { Cairo as FontSans } from "next/font/google"
import { cn } from "@/lib/utils"
import ConvexClientProvider from "./ConvexClientProvider";
import { ClerkProvider } from '@clerk/nextjs'
import { PrimeReactProvider } from 'primereact/api';
import 'primereact/resources/primereact.css';
import 'primereact/resources/themes/lara-light-indigo/theme.css';

const fontSans = FontSans({
  subsets: ["arabic"],
  variable: "--font-sans",
})
export const metadata: Metadata = {
  title: "Monhna Affiliate Marketing Program",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ar"
    >
      <body className={cn(
        "min-h-screen bg-background font-sans antialiased",
        fontSans.className
      )}>
        <PrimeReactProvider>
          <ClerkProvider >
            <ConvexClientProvider>
              {children}
            </ConvexClientProvider>
          </ClerkProvider>
        </PrimeReactProvider>
      </body>
    </html>
  );
}
