/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/oBOxMBYhjKo
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/components/ui/button"
import { CardHeader, CardContent, Card } from "@/components/ui/card"
import { ResponsiveLine } from "@nivo/line"
import { ResponsiveBar } from '@nivo/bar'
import { ShoppingBag, DollarSign, ClipboardIcon, WalletIcon } from 'lucide-react'
import { useEffect, useState } from "react";
import { CouponDetails } from '@/lib/types'
import Link from "next/link";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"
import { OrdersTable } from "./orders-table"
export function CouponCard({ couponCode }: { couponCode: string | undefined }) {
  const [copied, setCopied] = useState<boolean>(false);
  const [couponDetails, setCouponDetails] = useState<CouponDetails | null>(null)
  const copyToClipboard = () => {
    if (couponCode) {
      navigator.clipboard.writeText(couponCode)
        .then(() => {
          setCopied(true);
          console.log('Coupon code copied to clipboard!');
          setTimeout(() => setCopied(false), 1000);
        })
        .catch(err => {
          console.error('Failed to copy coupon code:', err);
        });
    }
  };

  useEffect(() => {
    if (couponCode) {
      const getCouponDetails = async () => {
        const res = await fetch(`${process.env.NEXT_PUBLIC_BACKEND_API_URL}/sales?coupon_code=${couponCode}`)
        const json = await res.json()
        console.log(json)
        if (res.status == 200) {
          setCouponDetails(json)
        }
      }
      getCouponDetails()
    }
  }, [couponCode])
  return (

    <Card className="w-full max-w-4xl  h-auto overflow-auto ">
      <CardHeader className="flex items-center justify-between">
        <div className="flex items-center gap-2">
          <div className="bg-primary px-3 py-1 rounded-full text-white text-sm font-medium">{couponCode}</div>
          <Button
            size="sm" variant="outline"
            onClick={() => {
              copyToClipboard()
            }}
          >
            <ClipboardIcon className="w-4 h-4" />
            {copied ? <span>تم النسخ</span> : <span>نسخ</span>}
          </Button>
        </div>
      </CardHeader>

      <CardContent className="grid gap-6 " dir="rtl">
        {couponDetails != null ?
          <>
            <div className="flex flex-col items-center justify-center bg-green-300 p-6 rounded-lg">
              <h2 className="text-2xl font-bold mb-2">عمولاتك</h2>
              <p className="text-8xl font-bold text-green-700">{couponDetails?.total_commission} <span className="text-4xl text-yellow-600">SAR</span></p>
              <Link href={`https://wa.me/966543486623?text=%D8%A3%D8%B1%D9%8A%D8%AF%20%D8%B3%D8%AD%D8%A8%20%D8%B9%D9%85%D9%88%D9%84%D8%A7%D8%AA%D9%8A%20%D9%83%D9%88%D8%AF%20%D8%A7%D9%84%D8%AE%D8%B5%D9%85%20%D8%A7%D9%84%D9%85%D9%85%D9%8A%D8%B2%20%D8%A7%D9%84%D8%AE%D8%A7%D8%B5%20%D8%A8%D9%8A%20%D9%87%D9%88%20${couponCode}`}>
                <Button className="mt-4">
                  <WalletIcon className="w-4 h-4 mr-2" />
                  اسحب عمولاتك
                </Button>
              </Link>
            </div>
            <div className="grid md:grid-cols-1 lg:grid-cols-3 gap-4">
              {/* Total Orders */}
              <Card className="bg-slate-300">
                <CardHeader>
                  <div className="flex gap-2 items-center">
                    <ShoppingBag className="w-5 h-5 text-gray-500 dark:text-gray-400" />
                    <span>جميع الطلبات</span>
                  </div>
                </CardHeader>
                <CardContent>
                  <p className="font-medium">
                    {couponDetails?.num_total_orders}
                  </p>
                </CardContent>
              </Card>

              {/* Total order value */}
              <Card className="bg-red-200">
                <CardHeader>
                  <div className="flex gap-2 items-center">
                    <DollarSign className="w-5 h-5 text-gray-500 dark:text-gray-400" />
                    <span>قيمة جميع الطلبات</span>
                  </div>
                </CardHeader>
                <CardContent>
                  <p className="font-medium">
                    {couponDetails?.total_order_value}
                  </p>
                </CardContent>
              </Card>

              {/* Average order value */}
              <Card className="bg-yellow-200">
                <CardHeader>
                  <div className="flex gap-2 items-center">
                    <DollarSign className="w-5 h-5 text-gray-500 dark:text-gray-400" />
                    <span>متوسط قيمة الطلب</span>
                  </div>
                </CardHeader>
                <CardContent>
                  <p className="font-medium">
                    {couponDetails?.average_order_value}
                  </p>
                </CardContent>
              </Card>
            </div>

            {/* Order Trend */}
            <div className="pt-20" />
            <div className="grid md:grid-cols-1 gap-6">
              <div>
                <h4 className="text-4xl mb-4">احصائيات عمولاتك مؤخرا</h4>
                <>

                  {couponDetails?.commission_stats &&
                    <>
                      <Tabs defaultValue="stats" className="w-full h-96" dir="rtl">
                        <TabsList>
                          <TabsTrigger value="stats">احصائيات</TabsTrigger>
                          <TabsTrigger value="details">تفاصيل</TabsTrigger>
                        </TabsList>
                        <TabsContent value="stats">
                          <div className="w-full h-96">
                            <BarChart
                              data={couponDetails.commission_stats}
                            ></BarChart>
                          </div>
                        </TabsContent>
                        <TabsContent value="details">
                          <OrdersTable couponCode={couponCode ?? ''}></OrdersTable>
                        </TabsContent>
                      </Tabs>
                    </>
                  }
                </>
              </div>
            </div>
          </>
          :
          <>
            <div className="text-7xl">
              Your Coupon didn't get any orders Yet
            </div>
          </>}


      </CardContent>
    </Card >
  )
}



const BarChart = ({ data }: { data: any }) => (
  <ResponsiveBar
    data={data}
    // keys={[
    //   'السعوديه',
    //   'الامارات',
    // ]}
    indexBy="month"
    margin={{ top: 50, right: 130, bottom: 50, left: 60 }}
    padding={0.3}
    valueScale={{ type: 'linear' }}
    indexScale={{ type: 'band', round: true }}
    colors={{ scheme: 'nivo' }}
    defs={[
      {
        id: 'dots',
        type: 'patternDots',
        background: 'inherit',
        color: '#38bcb2',
        size: 4,
        padding: 1,
        stagger: true
      },
      {
        id: 'lines',
        type: 'patternLines',
        background: 'inherit',
        color: '#eed312',
        rotation: -45,
        lineWidth: 6,
        spacing: 10
      }
    ]}
    fill={[
      {
        match: {
          id: 'fries'
        },
        id: 'dots'
      },
      {
        match: {
          id: 'sandwich'
        },
        id: 'lines'
      }
    ]}
    borderColor={{
      from: 'color',
      modifiers: [
        [
          'darker',
          1.6
        ]
      ]
    }}
    axisTop={null}
    axisRight={null}
    axisBottom={{
      tickSize: 5,
      tickPadding: 5,
      tickRotation: 0,
      legend: 'الزمن',
      legendPosition: 'middle',
      legendOffset: 32,
      truncateTickAt: 0
    }}
    axisLeft={{
      tickSize: 5,
      tickPadding: 5,
      tickRotation: 0,
      legend: 'العمولة',
      legendPosition: 'middle',
      legendOffset: -40,
      truncateTickAt: 0
    }}
    labelSkipWidth={12}
    labelSkipHeight={12}
    labelTextColor={{
      from: 'color',
      modifiers: [
        [
          'darker',
          1.6
        ]
      ]
    }}
    legends={[
      {
        dataFrom: 'keys',
        anchor: 'bottom-right',
        direction: 'column',
        justify: false,
        translateX: 120,
        translateY: 0,
        itemsSpacing: 2,
        itemWidth: 100,
        itemHeight: 20,
        itemDirection: 'left-to-right',
        itemOpacity: 0.85,
        symbolSize: 20,
        effects: [
          {
            on: 'hover',
            style: {
              itemOpacity: 1
            }
          }
        ]
      }
    ]}
    role="application"
    ariaLabel="Nivo bar chart demo"
    barAriaLabel={e => e.id + ": " + e.formattedValue + " in country: " + e.indexValue}
  />
)